### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-sinatra-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://zoboomafoo.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-intro/1) criteria:
- [x] display text when a user visits your homepage (e.g. `something.herokuapp.com`)
- [x] use Ruby to display the current year on the homepage
- [x] display text when a user visits an `/about` page (e.g. `something.herokuapp.com/about`)

**Comment by chrisvfritz** [comment]
:+1: :shipit: Excellent! Nothing needs to be "fixed" here, but one item that's worth noting is that calling functions/methods in Ruby does _not_ require parentheses, like this: `Time.now.year()`. Instead, `Time.now.year` works just as well and is typically preferred - especially when no arguments are being passed.

Let me know if that makes sense. :smiley:
